### PR TITLE
fix: use git commit -A

### PR DESCRIPTION
**Pull request by pmjhonwang**
https://stackoverflow.com/a/26039014

### CODE REVIEW

**Comment by pmjhonwang** [comment]
@JounQin  CR Request  pls

**Comment by JounQin** [comment]
@pmjhonwang Sorry I didn't notice this PR previously.

But I'm just wondering why are you using so old git version? Is GitLab old too?

**Comment by pmjhonwang** [comment]
> @pmjhonwang Sorry I didn't notice this PR previously.
> 
> But I'm just wondering why are you using so old git version? Is GitLab old too?

some gitlab runner is too old!

**Comment by JounQin** [comment]
@pmjhonwang It seems `git add -A` is already fine enough, no need `git add -A .`

**Comment by pmjhonwang** [comment]
> @pmjhonwang It seems `git add -A` is already fine enough, no need `git add -A .`
CleanShot 2022-02-15 at 15 06 14@2x

**Comment by pmjhonwang** [comment]
should these pr be merged?

**Pull request merged**
